# Generated by Django 4.0 on 2021-12-16 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamMember', '0004_remove_teammember_adminorregular'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='adminOrRegular',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
