# Generated by Django 4.0 on 2021-12-16 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamMember', '0006_alter_teammember_adminorregular'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='adminOrRegular',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Regular', 'Regular')], max_length=11),
        ),
    ]
