# Generated by Django 4.0 on 2021-12-16 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teamMember', '0007_alter_teammember_adminorregular'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teammember',
            old_name='email',
            new_name='Email',
        ),
        migrations.RenameField(
            model_name='teammember',
            old_name='firstName',
            new_name='FirstName',
        ),
        migrations.RenameField(
            model_name='teammember',
            old_name='lastName',
            new_name='LastName',
        ),
        migrations.RenameField(
            model_name='teammember',
            old_name='phoneNumber',
            new_name='PhoneNumber',
        ),
        migrations.RenameField(
            model_name='teammember',
            old_name='adminOrRegular',
            new_name='Role',
        ),
    ]
